<a href="https://colab.research.google.com/github/2303A52261/Generative-AI/blob/main/2303A52261_week8_ASS8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report



In [2]:
data = pd.read_csv("/content/winequality-red.csv")  # Update with actual path if needed


In [3]:
X = data.drop("quality", axis=1)
y = data["quality"]


In [4]:

y = pd.cut(y, bins=[0, 5, 6, 10], labels=[0, 1, 2])  # Adjust for classification


In [5]:
y = pd.get_dummies(y)  # One-hot encoding for ANN classification

In [6]:


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [8]:
model = keras.Sequential([
    keras.layers.Dense(16, activation='relu', input_shape=(X_train.shape[1],)),
    keras.layers.Dense(20, activation='relu'),
    keras.layers.Dense(25, activation='relu'),
    keras.layers.Dense(10, activation='relu'),
    keras.layers.Dense(y.shape[1], activation='softmax')  # Output layer
])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [9]:
model.compile(optimizer='adadelta', loss='categorical_crossentropy', metrics=['accuracy'])

In [10]:
history = model.fit(X_train, y_train, epochs=100, batch_size=64, validation_data=(X_test, y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.4337 - loss: 1.0596 - val_accuracy: 0.4344 - val_loss: 1.0796
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.4229 - loss: 1.0632 - val_accuracy: 0.4313 - val_loss: 1.0795
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.4327 - loss: 1.0709 - val_accuracy: 0.4313 - val_loss: 1.0794
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.4251 - loss: 1.0643 - val_accuracy: 0.4313 - val_loss: 1.0793
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.4264 - loss: 1.0699 - val_accuracy: 0.4313 - val_loss: 1.0793
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4126 - loss: 1.0666 - val_accuracy: 0.4344 - val_loss: 1.0792
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4161 - loss: 1.0713 - val_accuracy: 0.4344 - val_loss: 1.0791
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4342 - loss: 1.0761 - val_accuracy: 0.4

In [11]:

loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {accuracy}")


10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.4604 - loss: 1.0692  
Test Accuracy: 0.4437499940395355


In [12]:
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = np.argmax(y_test.values, axis=1)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step 


In [13]:
conf_matrix = confusion_matrix(y_true, y_pred_classes)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", classification_report(y_true, y_pred_classes))

Confusion Matrix:
 [[112  28   1]
 [102  30   0]
 [ 42   5   0]]
Classification Report:
               precision    recall  f1-score   support

           0       0.44      0.79      0.56       141
           1       0.48      0.23      0.31       132
           2       0.00      0.00      0.00        47

    accuracy                           0.44       320
   macro avg       0.30      0.34      0.29       320
weighted avg       0.39      0.44      0.38       320



In [14]:

model.save("wine_quality_model.h5")

In [15]:
def load_model():
    loaded_model = keras.models.load_model("wine_quality_model.h5")
    return loaded_model



In [16]:
loaded_model = load_model()
predictions = loaded_model.predict(X_test[:5])
print("Sample Predictions:", np.argmax(predictions, axis=1))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step
Sample Predictions: [0 0 0 0 1]
